version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_2404_AZPPProject
  gitServerName: SIQA_KVV_IBM
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
